apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name}}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}  
  resources:
    requests:
      storage: {{.Values.pvc.storageSize }}
